/**
 * compare-ai-quality.ts — Use AI to compare two quality test runs side-by-side.
 *
 * Usage:
 *   bun run scripts/compare-ai-quality.ts                    # compare the two most recent runs
 *   bun run scripts/compare-ai-quality.ts <run-a> <run-b>    # compare specific runs by folder name
 *
 * Requires: ANTHROPIC_API_KEY environment variable
 */

import Anthropic from "@anthropic-ai/sdk";
import { readdir, readFile, writeFile } from "fs/promises";
import { resolve, basename } from "path";
import { existsSync } from "fs";
import { computeCallCost, formatCallCost } from "../src/explain/api-cost.js";
import type { ApiCallCost } from "../src/explain/api-cost.js";

const RUNS_DIR = resolve(import.meta.dir, "..", "exampledata", "runs");

function log(msg: string): void {
  process.stderr.write(msg + "\n");
}

async function readFileOr(path: string): Promise<string | undefined> {
  if (!existsSync(path)) return undefined;
  return await readFile(path, "utf-8");
}

interface ProfileOutputs {
  explainNarrative?: string;
  deepFindings?: string;
  meta?: string;
}

async function loadProfileOutputs(runDir: string, profileName: string): Promise<ProfileOutputs | null> {
  const dir = resolve(runDir, profileName);
  if (!existsSync(dir)) return null;
  return {
    explainNarrative: await readFileOr(resolve(dir, "explain", "parsed-output.txt")),
    deepFindings: await readFileOr(resolve(dir, "deep", "parsed-findings.json")),
    meta: await readFileOr(resolve(dir, "meta.json")),
  };
}

function getModelFromMeta(metaJson: string | undefined): string {
  if (!metaJson) return "unknown";
  try {
    return JSON.parse(metaJson).model ?? "unknown";
  } catch {
    return "unknown";
  }
}

const COMPARE_SYSTEM_PROMPT = `You are a Business Central AL performance analysis expert reviewing AI-generated performance analysis outputs.

You are comparing two AI analyses of the SAME performance profile, generated by different models or configurations. Your job is to evaluate which analysis is more useful to a developer trying to fix performance issues.

## Evaluation Criteria

For each profile, evaluate both analyses on:

1. **Accuracy** — Are the findings factually correct based on what you can infer from the evidence? Are there any hallucinated or implausible claims?
2. **Actionability** — Do the suggestions give concrete, implementable fixes? Or are they vague ("optimize this", "consider caching")?
3. **Prioritization** — Are the most impactful issues ranked highest? Are severity/confidence ratings appropriate?
4. **Coverage** — Did one analysis catch important issues the other missed?
5. **Signal-to-noise** — Are there low-value or redundant findings that add noise without insight?
6. **BC domain knowledge** — Does the analysis show understanding of Business Central patterns (SetLoadFields, CalcFields, event subscribers, posting routines, etc.)?

## Output Format

For each profile, provide:
- A brief summary of what each analysis found
- Specific examples where one analysis was better or worse
- A verdict: which analysis is better for this profile, and why

At the end, provide an overall verdict across all profiles.

Be specific and cite finding titles. Don't be diplomatic — give a clear winner when there is one.`;

async function main(): Promise<void> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    log("ERROR: ANTHROPIC_API_KEY environment variable is not set");
    process.exit(1);
  }

  // Determine which two runs to compare
  const allRuns = (await readdir(RUNS_DIR)).sort();
  let runA: string;
  let runB: string;

  if (process.argv.length >= 4) {
    runA = process.argv[2];
    runB = process.argv[3];
    if (!allRuns.includes(runA)) {
      log(`ERROR: Run "${runA}" not found in ${RUNS_DIR}`);
      process.exit(1);
    }
    if (!allRuns.includes(runB)) {
      log(`ERROR: Run "${runB}" not found in ${RUNS_DIR}`);
      process.exit(1);
    }
  } else {
    if (allRuns.length < 2) {
      log("ERROR: Need at least 2 runs to compare. Run test-ai-quality.ts twice first.");
      process.exit(1);
    }
    runA = allRuns[allRuns.length - 2];
    runB = allRuns[allRuns.length - 1];
  }

  const runADir = resolve(RUNS_DIR, runA);
  const runBDir = resolve(RUNS_DIR, runB);

  // Discover profiles
  const aEntries = await readdir(runADir);
  const bEntries = await readdir(runBDir);
  const profileNames = [...new Set([
    ...aEntries.filter((e) => existsSync(resolve(runADir, e, "meta.json"))),
    ...bEntries.filter((e) => existsSync(resolve(runBDir, e, "meta.json"))),
  ])].sort();

  // Detect models from first profile's meta
  const firstA = await loadProfileOutputs(runADir, profileNames[0]);
  const firstB = await loadProfileOutputs(runBDir, profileNames[0]);
  const modelA = getModelFromMeta(firstA?.meta);
  const modelB = getModelFromMeta(firstB?.meta);

  log(`Comparing runs:`);
  log(`  A: ${runA} (model: ${modelA})`);
  log(`  B: ${runB} (model: ${modelB})`);
  log(`  Profiles: ${profileNames.length}`);

  // Build the comparison payload
  const sections: string[] = [];

  for (const name of profileNames) {
    const outputsA = await loadProfileOutputs(runADir, name);
    const outputsB = await loadProfileOutputs(runBDir, name);

    if (!outputsA && !outputsB) continue;

    let section = `## Profile: ${name}\n\n`;

    section += `### Analysis A (${modelA}, run ${runA})\n\n`;
    if (outputsA) {
      section += `#### Explain Narrative\n${outputsA.explainNarrative ?? "_not available_"}\n\n`;
      section += `#### Deep Findings\n${outputsA.deepFindings ?? "_not available_"}\n\n`;
    } else {
      section += "_Not available in this run_\n\n";
    }

    section += `### Analysis B (${modelB}, run ${runB})\n\n`;
    if (outputsB) {
      section += `#### Explain Narrative\n${outputsB.explainNarrative ?? "_not available_"}\n\n`;
      section += `#### Deep Findings\n${outputsB.deepFindings ?? "_not available_"}\n\n`;
    } else {
      section += "_Not available in this run_\n\n";
    }

    sections.push(section);
  }

  const userPayload = sections.join("\n---\n\n");

  log(`\nPayload size: ${(userPayload.length / 1024).toFixed(1)}KB`);
  log("Sending to Claude for comparison...\n");

  const client = new Anthropic({ apiKey });
  const response = await client.messages.create({
    model: "claude-sonnet-4-6",
    max_tokens: 8192,
    system: COMPARE_SYSTEM_PROMPT,
    messages: [{ role: "user", content: userPayload }],
  });

  const text = response.content
    .filter((b): b is Anthropic.TextBlock => b.type === "text")
    .map((b) => b.text)
    .join("");

  const cost = computeCallCost(
    "compare-quality",
    "claude-sonnet-4-6",
    response.usage.input_tokens,
    response.usage.output_tokens,
  );

  log(`Compare cost: ${formatCallCost(cost)}`);

  // Build the report
  const report = [
    `# AI Quality Comparison Report`,
    ``,
    `**Run A**: \`${runA}\` (model: ${modelA})`,
    `**Run B**: \`${runB}\` (model: ${modelB})`,
    `**Profiles compared**: ${profileNames.length}`,
    `**Comparison cost**: ${formatCallCost(cost)}`,
    ``,
    `---`,
    ``,
    text,
  ].join("\n");

  // Save to the newer run folder
  const reportPath = resolve(runBDir, "comparison-report.md");
  await writeFile(reportPath, report, "utf-8");
  log(`\nReport saved to: ${reportPath}`);

  // Also print to stdout for immediate reading
  process.stdout.write(report + "\n");
}

main().catch((err) => {
  log(`FATAL: ${err.message ?? err}`);
  process.exit(1);
});
