/**
 * compare-ai-quality-openrouter.ts — Neutral third-party judge for an AI quality A/B.
 *
 * Same payload + rubric as compare-ai-quality.ts, but the judge is an OpenRouter
 * model (default: google/gemini-3.1-pro-preview) instead of Anthropic Sonnet —
 * removes the self-preference bias of Sonnet judging Sonnet-vs-Opus.
 *
 * Usage:
 *   bun run scripts/compare-ai-quality-openrouter.ts <run-a> <run-b> [--model <slug>]
 *
 * Requires: OPENROUTER_API_KEY (Bun auto-loads .env)
 */

import { existsSync } from "fs";
import { readdir, readFile, writeFile } from "fs/promises";
import { resolve } from "path";

const RUNS_DIR = resolve(import.meta.dir, "..", "exampledata", "runs");
const OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions";

function log(msg: string): void {
	process.stderr.write(msg + "\n");
}

async function readFileOr(path: string): Promise<string | undefined> {
	if (!existsSync(path)) return undefined;
	return await readFile(path, "utf-8");
}

interface ProfileOutputs {
	explainNarrative?: string;
	deepFindings?: string;
	meta?: string;
}

async function loadProfileOutputs(
	runDir: string,
	profileName: string,
): Promise<ProfileOutputs | null> {
	const dir = resolve(runDir, profileName);
	if (!existsSync(dir)) return null;
	return {
		explainNarrative: await readFileOr(
			resolve(dir, "explain", "parsed-output.txt"),
		),
		deepFindings: await readFileOr(
			resolve(dir, "deep", "parsed-findings.json"),
		),
		meta: await readFileOr(resolve(dir, "meta.json")),
	};
}

function getModelFromMeta(metaJson: string | undefined): string {
	if (!metaJson) return "unknown";
	try {
		return JSON.parse(metaJson).model ?? "unknown";
	} catch {
		return "unknown";
	}
}

// Identical rubric to compare-ai-quality.ts so results are comparable.
const COMPARE_SYSTEM_PROMPT = `You are a Business Central AL performance analysis expert reviewing AI-generated performance analysis outputs.

You are comparing two AI analyses of the SAME performance profile, generated by different models or configurations. Your job is to evaluate which analysis is more useful to a developer trying to fix performance issues.

## Evaluation Criteria

For each profile, evaluate both analyses on:

1. **Accuracy** — Are the findings factually correct based on what you can infer from the evidence? Are there any hallucinated or implausible claims?
2. **Actionability** — Do the suggestions give concrete, implementable fixes? Or are they vague ("optimize this", "consider caching")?
3. **Prioritization** — Are the most impactful issues ranked highest? Are severity/confidence ratings appropriate?
4. **Coverage** — Did one analysis catch important issues the other missed?
5. **Signal-to-noise** — Are there low-value or redundant findings that add noise without insight?
6. **BC domain knowledge** — Does the analysis show understanding of Business Central patterns (SetLoadFields, CalcFields, event subscribers, posting routines, etc.)?

## Output Format

For each profile, provide:
- A brief summary of what each analysis found
- Specific examples where one analysis was better or worse
- A verdict: which analysis is better for this profile, and why

At the end, provide an overall verdict across all profiles, and a JSON block summarizing per-profile winners:
\`\`\`json
{ "profiles": [ { "name": "...", "winner": "A" | "B" | "tie", "reason": "..." } ], "overall": { "a_wins": 0, "b_wins": 0, "ties": 0, "verdict": "A" | "B" } }
\`\`\`

Be specific and cite finding titles. You are NOT one of the models being compared — judge impartially. Don't be diplomatic — give a clear winner when there is one.`;

function parseArgs(argv: string[]): {
	runA?: string;
	runB?: string;
	model: string;
} {
	const args = argv.slice(2);
	let model = "google/gemini-3.1-pro-preview";
	const positionals: string[] = [];
	for (let i = 0; i < args.length; i++) {
		if (args[i] === "--model" && i + 1 < args.length) {
			model = args[++i];
		} else {
			positionals.push(args[i]);
		}
	}
	return { runA: positionals[0], runB: positionals[1], model };
}

async function main(): Promise<void> {
	const { runA, runB, model } = parseArgs(process.argv);
	const apiKey = process.env.OPENROUTER_API_KEY;
	if (!apiKey) {
		log("ERROR: OPENROUTER_API_KEY not set (expected in .env)");
		process.exit(1);
	}
	if (!runA || !runB) {
		log("ERROR: provide two run folder names: <run-a> <run-b>");
		process.exit(1);
	}

	const runADir = resolve(RUNS_DIR, runA);
	const runBDir = resolve(RUNS_DIR, runB);
	for (const [name, dir] of [
		[runA, runADir],
		[runB, runBDir],
	] as const) {
		if (!existsSync(dir)) {
			log(`ERROR: run "${name}" not found in ${RUNS_DIR}`);
			process.exit(1);
		}
	}

	const aEntries = await readdir(runADir);
	const bEntries = await readdir(runBDir);
	const profileNames = [
		...new Set([
			...aEntries.filter((e) => existsSync(resolve(runADir, e, "meta.json"))),
			...bEntries.filter((e) => existsSync(resolve(runBDir, e, "meta.json"))),
		]),
	].sort();

	const firstA = await loadProfileOutputs(runADir, profileNames[0]);
	const firstB = await loadProfileOutputs(runBDir, profileNames[0]);
	const modelA = getModelFromMeta(firstA?.meta);
	const modelB = getModelFromMeta(firstB?.meta);

	log(`Judge: ${model} (via OpenRouter)`);
	log(`  A: ${runA} (model: ${modelA})`);
	log(`  B: ${runB} (model: ${modelB})`);
	log(`  Profiles: ${profileNames.length}`);

	const sections: string[] = [];
	for (const name of profileNames) {
		const a = await loadProfileOutputs(runADir, name);
		const b = await loadProfileOutputs(runBDir, name);
		if (!a && !b) continue;
		let s = `## Profile: ${name}\n\n`;
		s += `### Analysis A (${modelA})\n\n`;
		s += `#### Explain Narrative\n${a?.explainNarrative ?? "_not available_"}\n\n`;
		s += `#### Deep Findings\n${a?.deepFindings ?? "_not available_"}\n\n`;
		s += `### Analysis B (${modelB})\n\n`;
		s += `#### Explain Narrative\n${b?.explainNarrative ?? "_not available_"}\n\n`;
		s += `#### Deep Findings\n${b?.deepFindings ?? "_not available_"}\n\n`;
		sections.push(s);
	}
	const userPayload = sections.join("\n---\n\n");
	log(`\nPayload size: ${(userPayload.length / 1024).toFixed(1)}KB`);
	log("Sending to OpenRouter judge...\n");

	const resp = await fetch(OPENROUTER_URL, {
		method: "POST",
		headers: {
			Authorization: `Bearer ${apiKey}`,
			"Content-Type": "application/json",
			"X-Title": "al-perf AI quality A/B",
		},
		body: JSON.stringify({
			model,
			max_tokens: 16000,
			messages: [
				{ role: "system", content: COMPARE_SYSTEM_PROMPT },
				{ role: "user", content: userPayload },
			],
		}),
	});

	if (!resp.ok) {
		log(`ERROR: OpenRouter ${resp.status}: ${await resp.text()}`);
		process.exit(1);
	}
	const data = (await resp.json()) as {
		choices?: { message?: { content?: string }; finish_reason?: string }[];
		usage?: {
			prompt_tokens?: number;
			completion_tokens?: number;
			total_tokens?: number;
			cost?: number;
		};
	};
	const text = data.choices?.[0]?.message?.content ?? "";
	const finish = data.choices?.[0]?.finish_reason ?? "unknown";
	const u = data.usage ?? {};
	log(
		`Judge done. finish_reason=${finish}, tokens in/out=${u.prompt_tokens}/${u.completion_tokens}` +
			(u.cost != null ? `, cost=$${u.cost}` : ""),
	);
	if (finish === "length") {
		log("WARNING: judge output hit token cap — verdict may be truncated.");
	}

	const report = [
		`# AI Quality Comparison Report (neutral judge)`,
		``,
		`**Judge**: ${model} (OpenRouter)`,
		`**Run A**: \`${runA}\` (model: ${modelA})`,
		`**Run B**: \`${runB}\` (model: ${modelB})`,
		`**Profiles compared**: ${profileNames.length}`,
		`**Judge tokens**: in ${u.prompt_tokens ?? "?"} / out ${u.completion_tokens ?? "?"}` +
			(u.cost != null ? ` ($${u.cost})` : ""),
		``,
		`---`,
		``,
		text,
	].join("\n");

	const reportPath = resolve(runBDir, "comparison-report-gemini.md");
	await writeFile(reportPath, report, "utf-8");
	log(`\nReport saved to: ${reportPath}`);
	process.stdout.write(report + "\n");
}

main().catch((err) => {
	log(`FATAL: ${err.message ?? err}`);
	process.exit(1);
});
